kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-rhacm
  namespace: letschat
subjects:
  - kind: ServiceAccount
    name: mongodb-rhacm
    namespace: letschat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:nonroot'
