apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: letschat
spec:
  rsync:
    address: volsync-rsync-dst-letschat.letschat-volsync.svc.clusterset.local.
    copyMethod: Clone
    sshKeys: volsync-rsync-dst-src-letschat
    storageClassName: san
    volumeSnapshotClassName: ibm-block-fs7200-snapshot
  sourcePVC: mongodb
  trigger:
    schedule: '* * * * *'
