---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-pak-deployer-config
  namespace: cloud-pak-deployer
data:
  cpd-config.yaml: |
    global_config:
      environment_name: demo
      cloud_platform: existing-ocp
      confirm_destroy: False

    openshift:
    - name: cpd-demo
      ocp_version: "4.12"
      cluster_name: cpd-demo
      domain_name: example.com
      mcg:
        install: False
        storage_type: storage-class
        storage_class: managed-nfs-storage
      gpu:
        install: False
      openshift_storage:
      - ocp_storage_class_block: nfs
        ocp_storage_class_file: nfs
        storage_name: nfs
        storage_type: custom

    cp4d:
    - project: cpd
      openshift_cluster_name: "{{ env_id }}"
      cp4d_version: 4.8.2
      cp4d_entitlement: cpd-enterprise
      cp4d_production_license: True
      accept_licenses: True
      sequential_install: False
      db2u_limited_privileges: False
      use_fs_iam: True
      operators_project: cpd-operators
      cartridges:
      - name: cp-foundation
        license_service:
          state: disabled
          threads_per_core: 2
     
      - name: lite

      - name: scheduler
        state: installed

    #
    # All tested cartridges. To install, change the "state" property to "installed". To uninstall, change the state
    # to "removed" or comment out the entire cartridge. Make sure that the "-" and properties are aligned with the lite
    # cartridge; the "-" is at position 3 and the property starts at position 5.
    #

      # Please note that for watsonx.ai foundation models, you neeed to install the
      # Node Feature Discovery and NVIDIA GPU operators. You can do so by setting the openshift.gpu.install property to True
      - name: watsonx_ai
        description: watsonx.ai
        state: installed
        models:
        - model_id: google-flan-t5-xxl
          state: removed
        - model_id: google-flan-ul2
          state: removed
        - model_id: eleutherai-gpt-neox-20b
          state: removed
        - model_id: ibm-granite-13b-chat-v1
          state: removed
        - model_id: ibm-granite-13b-instruct-v1
          state: removed
        - model_id: meta-llama-llama-2-70b-chat
          state: removed
        - model_id: ibm-mpt-7b-instruct2
          state: removed
        - model_id: bigscience-mt0-xxl
          state: removed
        - model_id: bigcode-starcoder
          state: removed

      - name: watsonx_data
        description: watsonx.data
        state: removed
