kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  labels:
    app: letschat-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  #volumeName: pvc-letschat-mongodb