apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default-placement
  namespace: rhacm-policies
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: NotIn
              values:
                - "true"
