apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: telco-placement
  namespace: rhacm-policies
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: telco
              operator: In
              values:
                - "true"
