---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: lets-chat
  name: lets-chat
spec:
  lookupPolicy:
    local: false
