---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- lets-chat-deployment.yaml
#- namespace.yaml

# resources:
# - lets-chat-deployment.yaml
# - lets-chat-route.yaml
# - lets-chat-svc.yaml