---
apiVersion: v1
kind: Namespace
metadata:
  name: cloud-pak-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-pak-deployer-sa
  namespace: cloud-pak-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: cloud-pak-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: cloud-pak-deployer-sa
  namespace: cloud-pak-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-pak-deployer-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cloud-pak-deployer-sa
  namespace: cloud-pak-deployer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-pak-deployer-status
  namespace: cloud-pak-deployer
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cloud-pak-deployer
  name: cloud-pak-deployer
  namespace: cloud-pak-deployer
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: cloud-pak-deployer
      labels:
        app: cloud-pak-deployer
    spec:
      containers:
      - name: cloud-pak-deployer
        image: quay.io/cloud-pak-deployer/cloud-pak-deployer:latest
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: STATUS_DIR
            value: /Data/cpd-status
          - name: CPD_CONFIG_GIT_CONTEXT
            value: policy-sets/cloudpak-deployer/configs/{{hub .ManagedClusterName hub}}
          - name: CPD_CONFIG_GIT_REF
            value: main
          - name: CPD_CONFIG_GIT_REPO
            value: https://github.com/ibm-garage-mop/rhacm.git
          - name: CPD_WIZARD_MODE
            value: existing-ocp
          - name: CP_ENTITLEMENT_KEY
            valueFrom:
              secretKeyRef:
               name: cloud-pak-entitlement-key
               key: cp-entitlement-key
        volumeMounts:
        - name: status-volume
          mountPath: /Data/cpd-status
        command: ["/bin/sh","-xc"]
        args: 
        # /cloud-pak-deployer/cp-deploy.sh vault set -vs cp4d_admin_zen_sample_sample -vsv "my Really Sec3re Passw0rd" && /cloud-pak-deployer/cp-deploy.sh env apply -v --cp-config-only
          - /cloud-pak-deployer/cp-deploy.sh env apply -v --accept-all-licenses
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      serviceAccountName: cloud-pak-deployer-sa
      volumes:
      - name: status-volume
        persistentVolumeClaim:
          claimName: cloud-pak-deployer-status    
