apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../policy-sets/default

#generators:
#- policyGenerator-virtualization-target.yaml

# labels:
# - includeSelectors: true
#   pairs:
#     env: prod
