apiVersion: v1
data: '{{hub copySecretData "rhacm-policies" "htpasswd-admins" hub}}'
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-secret
      mappingMethod: add
      name: local-admins
      type: HTPasswd