apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default
  - telco-stack/all
  - telco-stack/virtualization-target
  - cloudpak-deployer

#generators:
#- policyGenerator-virtualization-target.yaml

# labels:
# - includeSelectors: true
#   pairs:
#     env: prod
