apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2adv
  namespace: metallb
--- 
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ipapool
  namespace: metallb
spec:
  addresses:
    - 172.19.0.160-172.19.0.169