apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-481-ens2f1
spec:
  desiredState:
    interfaces:
      - description: VLAN using ens2f1
        name: ens2f1.483
        state: up
        type: vlan
        vlan:
          base-iface: ens2f1
          id: 483
  nodeSelector:
    node-role.kubernetes.io/worker: ''
