apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    apps.open-cluster-management.io/cluster-admin: "true"
    apps.open-cluster-management.io/hosting-subscription: rhacm-policies/policies-subscription-1-local
    apps.open-cluster-management.io/reconcile-option: merge
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: Access Control
    policy.open-cluster-management.io/standards: IBM MOP
  labels:
    app: policies
    app.kubernetes.io/part-of: policies
    apps.open-cluster-management.io/reconcile-rate: medium
  name: group-admins
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: group-ocp-admins
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: user.openshift.io/v1
                kind: Group
                metadata:
                  name: ocp-admins
                users:
                  - sophie
                  - schabrolles
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: ocp-cluster-admins
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
                subjects:
                  - apiGroup: rbac.authorization.k8s.io
                    kind: Group
                    name: ocp-admins
          severity: high
  remediationAction: enforce
