apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: Authentication
    policy.open-cluster-management.io/standards: IBM MOP
  name: oauth-htpasswd
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oauth-htpasswd
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - htpasswd:
                        fileData:
                          name: htpasswd-secret
                      mappingMethod: add
                      name: local-admins
                      type: HTPasswd
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data: '{{hub copySecretData "rhacm-policies" "htpasswd-admins" hub}}'
                kind: Secret
                metadata:
                  name: htpasswd-secret
                  namespace: openshift-config
                type: Opaque
          remediationAction: enforce
          severity: medium
  remediationAction: enforce
