apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    apps.open-cluster-management.io/cluster-admin: "true"
    apps.open-cluster-management.io/hosting-subscription: rhacm-policies/policies-subscription-1-local
    apps.open-cluster-management.io/reconcile-option: merge
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: Network
  labels:
    app: policies
    app.kubernetes.io/part-of: policies
    apps.open-cluster-management.io/reconcile-rate: medium
  name: sriov-cfg-default
  namespace: rhacm-policies
spec:
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
      name: sriov-operator
      namespace: rhacm-policies
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sriov-cfg-default
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: sriovnetwork.openshift.io/v1
                kind: SriovOperatorConfig
                metadata:
                  name: default
                  namespace: openshift-sriov-network-operator
                spec:
                  configDaemonNodeSelector:
                    ran.openshift.io/sriov: ""
                  enableInjector: true
                  enableOperatorWebhook: true
                  logLevel: 2
          pruneObjectBehavior: None
          remediationAction: inform
          severity: low
  remediationAction: enforce
